const MFAPI_BASE='https://api.mfapi.in';
const AMFI_NAV_URL='https://portal.amfiindia.com/spages/NAVAll.txt';
const CACHE_TTL=5*60*1000;
const STALE_TTL=24*60*60*1000;
function cache(){globalThis.__ML_CACHE__??=new Map();return globalThis.__ML_CACHE__}
function codeOf(v){const s=String(v??'').trim();return /^\d{4,9}$/.test(s)?Number(s):null}
async function fetchTimeout(url,ms=12000){const c=new AbortController();const t=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{cache:'no-store',signal:c.signal,headers:{accept:'application/json,text/plain,*/*','user-agent':'managerlens/1.2'}})}finally{clearTimeout(t)}}
function iso(d){const p=String(d||'').split('-');if(p.length===3&&p[0].length===2)return `${p[2]}-${p[1]}-${p[0]}`;const x=new Date(d);return Number.isFinite(x.getTime())?x.toISOString().slice(0,10):null}
function parseAmfi(text){return String(text||'').split(/\r?\n/).filter(x=>/^\d+;/.test(x.trim())).map(x=>{const p=x.trim().split(';');return{schemeCode:Number(p[0]),schemeName:p[3],nav:Number(p[4]),date:p[5]}}).filter(x=>x.schemeCode&&x.schemeName)}
async function amfiRows(){const c=cache(),k='amfi',now=Date.now(),old=c.get(k);if(old&&now-old.at<CACHE_TTL)return old.value;try{const r=await fetchTimeout(AMFI_NAV_URL,10000);if(!r.ok)throw Error(`AMFI ${r.status}`);const rows=parseAmfi(await r.text());if(!rows.length)throw Error('AMFI returned no schemes');const value={rows,fetchedAt:new Date().toISOString()};c.set(k,{at:now,value});return value}catch(e){if(old&&now-old.at<STALE_TTL)return old.value;throw e}}
function norm(s){return String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function score(name,q){const n=norm(name),t=norm(q),tokens=t.split(' ').filter(Boolean);let s=n===t?120:n.includes(t)?60:0;for(const token of tokens)if(n.includes(token))s+=token.length>5?8:4;if(n.includes('direct'))s+=25;if(n.includes('growth'))s+=25;if(n.includes('regular'))s-=45;if(n.includes('idcw')||n.includes('dividend'))s-=35;return s-tokens.filter(x=>!n.includes(x)).length*8}
async function resolveByCode(raw){const schemeCode=codeOf(raw);if(!schemeCode)throw Error('AMFI scheme code must contain 4 to 9 digits.');let row=null;try{row=(await amfiRows()).rows.find(x=>x.schemeCode===schemeCode)||null}catch{};let meta=null;try{const r=await fetchTimeout(`${MFAPI_BASE}/mf/${schemeCode}/latest`,9000);if(r.ok)meta=(await r.json()).meta||null}catch{};if(!row&&!meta)throw Error(`Scheme code ${schemeCode} was not found in AMFI or MFapi.`);return{schemeCode,schemeName:row?.schemeName||meta?.scheme_name||`Scheme ${schemeCode}`,resolvedBy:row?'Direct AMFI scheme code':'Direct MFapi scheme code',amfiRow:row}}
async function resolveByQueries(queries){let candidates=[];for(const q of queries){try{const r=await fetchTimeout(`${MFAPI_BASE}/mf/search?q=${encodeURIComponent(q)}`,8000);if(r.ok){for(const x of await r.json())if(!candidates.some(y=>y.schemeCode===x.schemeCode))candidates.push(x)}}catch{}}if(!candidates.length){try{candidates=(await amfiRows()).rows.map(x=>({schemeCode:x.schemeCode,schemeName:x.schemeName}))}catch{}}let best=null;for(const x of candidates)for(const q of queries){const s=score(x.schemeName,q);if(!best||s>best.score)best={...x,score:s,query:q}}if(!best||best.score<20)throw Error(`No MFapi/AMFI match found for ${queries.join(' | ')}`);return{schemeCode:Number(best.schemeCode),schemeName:best.schemeName,resolvedBy:'Ranked MFapi/AMFI search'}}
async function historyRequest(code,startDate,endDate){const p=new URLSearchParams();if(startDate)p.set('startDate',startDate);if(endDate)p.set('endDate',endDate);const r=await fetchTimeout(`${MFAPI_BASE}/mf/${code}${p.toString()?`?${p}`:''}`,12000);if(!r.ok)throw Error(`MFapi history ${r.status}`);return r.json()}
async function history(code,startDate,endDate){try{const ranged=await historyRequest(code,startDate,endDate);if(Array.isArray(ranged.data)&&ranged.data.length)return ranged}catch{}const full=await historyRequest(code);if(!Array.isArray(full.data)||!full.data.length)throw Error('MFapi returned no NAV history.');const data=full.data.filter(x=>{const d=iso(x.date);return d&&(!startDate||d>=startDate)&&(!endDate||d<=endDate)});if(!data.length)throw Error('No NAV observations exist in the selected date range.');return{...full,data,fallback:'full-history-local-filter'}}
async function liveSeries({queries=[],schemeCode,startDate,endDate}){const direct=codeOf(schemeCode);const key=`series:${direct||JSON.stringify(queries)}:${startDate||''}:${endDate||''}`,c=cache(),now=Date.now(),old=c.get(key);if(old&&now-old.at<CACHE_TTL)return{...old.value,cache:'fresh'};try{const resolved=direct?await resolveByCode(direct):await resolveByQueries(queries);const h=await history(resolved.schemeCode,startDate,endDate);let latest=resolved.amfiRow||null;try{latest??=(await amfiRows()).rows.find(x=>x.schemeCode===resolved.schemeCode)||null}catch{}const value={ok:true,meta:h.meta||{},data:h.data,source:{primary:'MFapi.in',validation:'AMFI NAVAll',schemeCode:resolved.schemeCode,schemeName:resolved.schemeName,resolvedBy:resolved.resolvedBy,amfiStatus:latest?'validated':'unavailable',amfiLatest:latest,historyFallback:h.fallback||null,fetchedAt:new Date().toISOString(),stale:false}};c.set(key,{at:now,value});return value}catch(e){if(old&&now-old.at<STALE_TTL)return{...old.value,cache:'stale',source:{...old.value.source,stale:true,warning:e.message}};throw e}}
async function health(){const [m,a]=await Promise.allSettled([fetchTimeout(`${MFAPI_BASE}/mf/125497/latest`,7000),fetchTimeout(AMFI_NAV_URL,7000)]);return{checkedAt:new Date().toISOString(),mfapi:m.status==='fulfilled'&&m.value.ok?'online':'degraded',amfi:a.status==='fulfilled'&&a.value.ok?'online':'degraded'}}
export{codeOf,resolveByCode,history,liveSeries,health};
